[package]
name = "cybersec-wow"
version = "0.1.0"
edition = "2024"
author = "Usher Craig"

[dependencies]
base16ct = "0.2.0"
iced = { version = "0.13.1", features = ["tokio", "wgpu"] }
reqwest = "0.12.15"
sha1 = "0.10.6"
tokio = { version = "1.44.1", features = ["full"] }
